# TownyWands - Custom Towny GUI's | Configuration (v1.0.6)
# -- Dont change this --
configVersion: 137
# -- Dont change this --
# Important Notes:
# If you dont know what 'metaID' means: its the last part of the full item id, for example: 17:3 , the metaID comes behind the ':', if the item you want to add has no metaID, set it to 0 (zero)
# Dont enter higher slot values than your inventory supports, so if your GUI has 18 slots, dont use values lower than 1 or higher than 18 or you will get bombed by a ton of errors :D
# If you want to add more languages, just add the fields: name_ , lore_ , commands_ , each followed by your wished langcode, for example: es_ES = Spanish | fr_FR = Francais
# You can find all supported languages and their langcodes on the GitHub page! :) -> https://github.com/FastFelix771/TownyWands/blob/master/README.md
# Should TownyWands send some anonymous data to mcstats.org? 
metrics: true
# EXPERIMENTAL | If you wish to use auto-translating you only need to provide english text as base for all translations that are possible.
auto-translate: false
# EXPERIMENTAL | If the english base-texts are missing, it will throw errors, but the default config contains english texts, so you should be able to use this feature without problems.
# Commands will not get auto-translated, it will just use the english pattern.
# The first translation will take some time, then it will save the translated data and re-use it on the next restart if the english entries hasn't changed.
cpu-threads: 4
# More threads will allow to parse more inventories at the same time.
# Should TownyWands check if theres a new version of the plugin? It will NOT download anything, it will just tell you if theres a newer version of the plugin!
checkForUpdates: true