name: TownyWands
version: 2.0.2
author: FastFelix771
main: me.fastfelix771.townywands.main.TownyWands
soft-depend: [Towny, TownyChat, Vault, PermissionsEx, Essentials, WorldEdit, WorldGuard, Factions, MassiveCore]
commands:
   townywands:
     description: Provides basic features.
     usage: /townywands ?
   gui:
     description: Creation and changing of GUIs
     usage: /gui help
   vsign:
     description: Creates a virtual Sign and executes commands from the given input.
     usage: /vsign playername command {data}
   bungeetp:
     description: Teleports a player to another server in your bungeecord network.
     usage: /bungeetp playername servername
   fakecmd:
     description: Let players execute fake commands, wich most alias plugins and TownyChat uses.
     usage: /fakecmd playername commandToExecute