name: TownyWands
version: 2.1.1
author: FastFelix771
main: de.fastfelix771.townywands.main.TownyWands
depend: [ProtocolLib]
commands:
   townywands:
     description: Provides basic features.
     usage: /townywands ?
     aliases: [tws]
   vsign:
     description: Creates a virtual Sign and executes commands from the given input.
     usage: /vsign <player> <command {data}>
   bungeetp:
     description: Teleports a player to another server in your bungeecord network.
     usage: /bungeetp <player> <servername>
   fakecmd:
     description: Let players execute fake commands, which most alias plugins and TownyChat uses.
     usage: /fakecmd <player> <command>
   modify:
     description: Modify Items!
     usage: /modify help
   gui:
     description: Modify GUIs!
     usage: /gui help
   inv:
     description: Modify Inventories!
     usage: /inv help