name: TownyWands
version: 1.0.8
author: FastFelix771
main: me.fastfelix771.townywands.main.Mainclass
soft-depend: [Towny, Vault, PermissionsEx, Essentials]
commands:
   townywands:
     description: Provides basic features.
     usage: /townywands ?
   gui:
     description: Creation and changing of GUIs
     usage: /gui help
   vsign:
     description: Creates a virtual Sign and executes commands from the given input.
     usage: /vsign playername command {data}
   bungeetp:
     description: Teleports a player to another server in your bungeecord network.
     usage: /bungeetp playername servername