name: TownyWands
version: 1.0.5
author: FastFelix771
main: me.fastfelix771.townywands.main.Mainclass
soft-depend: [Towny]
commands:
   townywands:
     description: Provides fuctions for reloading TownyWands & more.
     usage: /townywands ?