name: TownyWands
version: 1.1
author: FastFelix771
main: me.fastfelix771.townywands.main.Mainclass
depend: [Towny]
soft-depend:
commands:
   twa:
     description: Opens the TownyWands Admin GUI
     usage:
   twu:
     description: Opens the TownyWands User GUI
     usage: