name: TownyWands
version: 2.1.0-SNAPSHOT
author: FastFelix771
main: de.fastfelix771.townywands.main.TownyWands
database: true
depend: [ProtocolLib]
commands:
   townywands:
     description: Provides basic features.
     usage: /townywands ?
     aliases: [tws]
   vsign:
     description: Creates a virtual Sign and executes commands from the given input.
     usage: /vsign playername command {data}
   bungeetp:
     description: Teleports a player to another server in your bungeecord network.
     usage: /bungeetp playername servername
   fakecmd:
     description: Let players execute fake commands, wich most alias plugins and TownyChat uses.
     usage: /fakecmd playername commandToExecute